title: Youjin's AI Engineering Notes
description: "AI 연구, 논문 리뷰와 개발 경험을 기록하는 이유진의 기술 블로그"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"
url: "https://jinleey126.github.io"
lang: ko-KR

# Social Links
email: jinleey126@gmail.com
github_username: jinleey126

# External API
# giscus_repo:
# giscus_repoId:
# giscus_category:
# giscus_categoryId:
# goatcounter_code:
# google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl: ""

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/
  - guideline.md
  - README.md
  - vendor/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown settings
kramdown:
  input: GFM
  hard_wrap: false
